spring:      
  datasource:
    url: jdbc:mysql://localhost:3306/cardshopdb?createDatabaseIfNotExist=true&serverTimezone=GMT%2B8
    username: pm
    password: pm
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true   
  servlet:
    multipart: 
      max-file-size: 10MB
      max-request-size: 100MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest 
    virtual-host: /             
#  mvc:
#    static-path-pattern: /res/**
#  web:
#    resources: 
#      static-locations: classpath:/static/
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 80
  servlet:
    session:
      timeout: 0
    encoding: 
      charset: UTF-8
      force: true
      enabled: true      
  tomcat:
    uri-encoding: UTF-8
    
cardstore:
 path: C:\myproject\testimg\    
  
