spring:
  profiles:
    active: dev
  servlet:
    multipart: 
      max-file-size: 20MB
      max-request-size: 100MB    
springdoc:
  default-produces-media-type: application/json   
        
#server:
#  servlet:
#    context-path: 